# Generated by Django 4.0.4 on 2022-06-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_producto_descripcion_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto_producto',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
