# Generated by Django 4.0.4 on 2022-06-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_producto_foto_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipoanimal_producto',
            field=models.IntegerField(max_length=1, null=True),
        ),
    ]
